packages:
  - "apps/*"
  - "packages/*"
minimumReleaseAgeExclude:
  - "@deepseek-ai/*"
overrides:
  "app-builder-lib>@electron/get": "5.1.0"
allowBuilds:
  electron: true
  electron-winstaller: true
  '@deepseek-ai/dsh-subprocess-local': true
  '@google/genai': true
  cpu-features: true
  esbuild: true
  koffi: true
  node-pty: true
  protobufjs: true
  ssh2: true
