import type { WorldThemeManifestV1 } from '@dsh-cyber/contracts'

const blocked = [
  '2,4', '3,4', '4,4', '5,4', '6,4',
  '11,4', '12,4', '13,4', '14,4', '15,4', '16,4', '17,4',
  '22,4', '23,4', '24,4',
  '3,14', '4,14', '5,14', '6,14', '7,14',
  '23,16', '24,16', '25,16', '26,16',
]

export const cyberCompanyTheme: WorldThemeManifestV1 = {
  schemaVersion: 1,
  id: 'dsh-cyber.company.nocturne',
  version: '2.0.0',
  templateId: 'company',
  displayName: '赛博公司 · 夜班总部',
  renderer: 'pixi-2d',
  terminology: {
    world: '公司',
    participant: '角色',
    session: '协作频道',
    milestone: '成长事迹',
  },
  assets: [
    {
      id: 'office-scene',
      src: '/assets/cyber-office-world-clean.png',
      kind: 'image',
      preload: true,
      pixelArt: true,
    },
    {
      id: 'company-roster',
      src: '/assets/employee-roster-transparent.png',
      kind: 'spritesheet',
      preload: true,
      pixelArt: false,
    },
  ],
  actorSets: [
    {
      id: 'company-roster-v1',
      assetId: 'company-roster',
      frameWidth: 384,
      frameHeight: 512,
      scale: 0.25,
      footOffset: { x: 0, y: 112 },
      clips: {
        idle: { south: [0], north: [0], east: [0], west: [0] },
        walking: { south: [0], north: [0], east: [0], west: [0] },
        thinking: { south: [0], north: [0], east: [0], west: [0] },
        working: { south: [0], north: [0], east: [0], west: [0] },
        talking: { south: [0], north: [0], east: [0], west: [0] },
        meeting: { south: [0], north: [0], east: [0], west: [0] },
        blocked: { south: [0], north: [0], east: [0], west: [0] },
        celebrating: { south: [0], north: [0], east: [0], west: [0] },
      },
    },
  ],
  scenes: [
    {
      id: 'headquarters',
      displayName: '总部运行层',
      size: { width: 1440, height: 1080 },
      cameraBounds: { x: 24, y: 24, width: 1392, height: 1032 },
      safeArea: { x: 52, y: 52, width: 1336, height: 976 },
      layers: [
        {
          id: 'floor-and-walls',
          assetId: 'office-scene',
          destination: { x: 0, y: 0, width: 1440, height: 1080 },
          zIndex: 0,
        },
        {
          id: 'top-desk-fronts',
          assetId: 'office-scene',
          source: { x: 130, y: 286, width: 1050, height: 118 },
          destination: { x: 130, y: 286, width: 1050, height: 118 },
          zIndex: 540,
          occludesActors: true,
        },
        {
          id: 'ops-desk-front',
          assetId: 'office-scene',
          source: { x: 156, y: 745, width: 265, height: 110 },
          destination: { x: 156, y: 745, width: 265, height: 110 },
          zIndex: 850,
          occludesActors: true,
        },
        {
          id: 'meeting-table-front',
          assetId: 'office-scene',
          source: { x: 1150, y: 865, width: 255, height: 135 },
          destination: { x: 1150, y: 865, width: 255, height: 135 },
          zIndex: 1000,
          occludesActors: true,
        },
      ],
      anchors: [
        { id: 'spawn', position: { x: 718, y: 946 }, facing: 'north', capacity: 8, tags: ['spawn'] },
        { id: 'work-product', position: { x: 245, y: 365 }, facing: 'north', capacity: 1, tags: ['work', 'product'] },
        { id: 'work-architecture', position: { x: 650, y: 376 }, facing: 'north', capacity: 2, tags: ['work', 'architecture'] },
        { id: 'work-engineering', position: { x: 1108, y: 372 }, facing: 'north', capacity: 1, tags: ['work', 'engineering'] },
        { id: 'ops-console', position: { x: 295, y: 838 }, facing: 'north', capacity: 2, tags: ['work', 'ops'] },
        { id: 'milestone-wall', position: { x: 718, y: 575 }, facing: 'north', capacity: 4, tags: ['inspect', 'milestone'] },
        { id: 'meeting-west', position: { x: 1130, y: 900 }, facing: 'east', capacity: 1, tags: ['meeting'] },
        { id: 'meeting-east', position: { x: 1380, y: 900 }, facing: 'west', capacity: 1, tags: ['meeting'] },
        { id: 'meeting-south', position: { x: 1260, y: 1020 }, facing: 'north', capacity: 2, tags: ['meeting'] },
        { id: 'lounge', position: { x: 1110, y: 740 }, facing: 'south', capacity: 3, tags: ['idle', 'talk'] },
      ],
      navigation: {
        origin: { x: 0, y: 0 },
        cellSize: 48,
        columns: 30,
        rows: 23,
        blocked,
      },
      interactables: [
        {
          id: 'workstation',
          kind: 'workstation',
          displayName: '研发工作站',
          bounds: { x: 505, y: 180, width: 380, height: 230 },
          approachAnchorIds: ['work-architecture'],
          actions: [
            { id: 'assign-task', label: '安排任务' },
            { id: 'inspect', label: '查看当前执行' },
          ],
          zIndex: 150,
        },
        {
          id: 'meeting-table',
          kind: 'meeting-table',
          displayName: '协作会议桌',
          bounds: { x: 1110, y: 820, width: 300, height: 205 },
          approachAnchorIds: ['meeting-west', 'meeting-east', 'meeting-south'],
          actions: [{ id: 'start-meeting', label: '召集会议' }],
          zIndex: 170,
        },
        {
          id: 'ops-console',
          kind: 'ops-console',
          displayName: '运行控制台',
          bounds: { x: 150, y: 635, width: 290, height: 230 },
          approachAnchorIds: ['ops-console'],
          actions: [
            { id: 'use-object', label: '查看运行轨迹' },
            { id: 'assign-task', label: '发起巡检' },
          ],
          zIndex: 160,
        },
        {
          id: 'milestone-wall',
          kind: 'milestone-wall',
          displayName: '成长里程碑墙',
          bounds: { x: 620, y: 500, width: 200, height: 170 },
          approachAnchorIds: ['milestone-wall'],
          actions: [{ id: 'inspect', label: '查看角色成长' }],
          zIndex: 140,
        },
      ],
      growthSlots: [
        { id: 'growth-1', category: 'skill', position: { x: 690, y: 525 }, zIndex: 125 },
        { id: 'growth-2', category: 'delivery', position: { x: 735, y: 525 }, zIndex: 125 },
        { id: 'growth-3', category: 'promotion', position: { x: 780, y: 525 }, zIndex: 125 },
      ],
    },
  ],
  activityMapping: {
    'task.started': 'working',
    'turn.started': 'thinking',
    'tool.started': 'working',
    'message.appended': 'talking',
    'task.blocked': 'blocked',
    'task.completed': 'idle',
    'meeting.started': 'meeting',
    'meeting.finished': 'idle',
  },
}
