import { LockKey, Palette, SlidersHorizontal, UserCircle, X } from '@phosphor-icons/react'
import { useEffect, useState } from 'react'
import type { ModelProfile, ReasoningEffort, World, WorldAccessSummary, WorldSettings } from '@dsh-cyber/contracts'

export function WorldSettingsDialog({ world, value, access, models, saving, onClose, onSave, onSetPassword, onClearPassword, onLock }: { world: World; value: WorldSettings; access: WorldAccessSummary; models: ModelProfile[]; saving: boolean; onClose(): void; onSave(value: WorldSettings): Promise<void>; onSetPassword(password: string): Promise<void>; onClearPassword(): Promise<void>; onLock(): Promise<void> }) {
  const [draft, setDraft] = useState(value)
  const [password, setPassword] = useState('')
  useEffect(() => setDraft(value), [value])
  return <div className="modal-backdrop" role="presentation" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><section className="world-settings-dialog" role="dialog" aria-modal="true"><header className="dialog-header"><div><h2>世界设置 · {world.name}</h2><p>这些设置只属于当前世界，不会影响其他世界。</p></div><button className="icon-button" onClick={onClose} aria-label="关闭"><X size={18}/></button></header><div className="world-settings-grid">
    <fieldset><legend><SlidersHorizontal size={16}/> 世界观</legend><label>世界设定<textarea rows={6} value={draft.lore} onChange={(e)=>setDraft({...draft,lore:e.target.value})} placeholder="例如：这是一个雨夜魔法学院，我是院长，所有角色都知道学院的基本规则……"/></label><label>当前场景<textarea rows={3} value={draft.scenario} onChange={(e)=>setDraft({...draft,scenario:e.target.value})}/></label></fieldset>
    <fieldset><legend><UserCircle size={16}/> 你与角色</legend><label>你的名字<input value={draft.userIdentity.displayName} onChange={(e)=>setDraft({...draft,userIdentity:{...draft.userIdentity,displayName:e.target.value}})}/></label><label>你在世界里的身份<input value={draft.userIdentity.worldRole} onChange={(e)=>setDraft({...draft,userIdentity:{...draft.userIdentity,worldRole:e.target.value}})} placeholder="主人 / 老板 / 院长 / 旅人"/></label><label>角色如何称呼你<input value={draft.userIdentity.addressAs} onChange={(e)=>setDraft({...draft,userIdentity:{...draft.userIdentity,addressAs:e.target.value}})}/></label><label>单个角色称呼<input value={draft.terminology.characterSingular} onChange={(e)=>setDraft({...draft,terminology:{...draft.terminology,characterSingular:e.target.value}})}/></label></fieldset>
    <fieldset><legend><Palette size={16}/> 视觉</legend><div className="color-setting-row"><label>强调色<input type="color" value={draft.appearance.accentColor} onChange={(e)=>setDraft({...draft,appearance:{...draft.appearance,accentColor:e.target.value}})}/></label><label>背景<input type="color" value={draft.appearance.pageBackground} onChange={(e)=>setDraft({...draft,appearance:{...draft.appearance,pageBackground:e.target.value}})}/></label><label>角色气泡<input type="color" value={draft.appearance.characterBubbleColor} onChange={(e)=>setDraft({...draft,appearance:{...draft.appearance,characterBubbleColor:e.target.value}})}/></label></div><label>对话框圆角 <input type="range" min="0" max="28" value={draft.appearance.bubbleRadius} onChange={(e)=>setDraft({...draft,appearance:{...draft.appearance,bubbleRadius:Number(e.target.value)}})}/></label></fieldset>
    <fieldset><legend><SlidersHorizontal size={16}/> 模型与推理</legend><label>世界默认模型<select value={draft.model.defaultModelProfileId ?? ''} onChange={(e)=>setDraft({...draft,model:e.target.value ? {...draft.model,defaultModelProfileId:e.target.value} : {reasoningEffort:draft.model.reasoningEffort}})}><option value="">跟随全局/角色设置</option>{models.map((model)=><option key={model.id} value={model.id}>{model.displayName} · {model.modelId}</option>)}</select></label><label>默认推理<select value={draft.model.reasoningEffort} onChange={(e)=>setDraft({...draft,model:{...draft.model,reasoningEffort:e.target.value as ReasoningEffort}})}>{['auto','off','minimal','low','medium','high','xhigh','max'].map((id)=><option key={id} value={id}>{({auto:'自动',off:'关闭',minimal:'极低',low:'低',medium:'中',high:'高',xhigh:'极高',max:'最大'} as Record<string,string>)[id]}</option>)}</select></label></fieldset>
    <fieldset><legend><LockKey size={16}/> 隐私</legend><p>{access.passwordEnabled ? '当前世界已启用本地访问锁。密码不会明文保存。' : '可为当前世界单独设置访问密码。第一阶段是本机访问锁，不等同磁盘加密。'}</p>{access.passwordEnabled ? <div className="settings-inline-actions"><button className="secondary-button" onClick={()=>void onLock()}>立即锁定</button><button className="text-button" onClick={()=>void onClearPassword()}>移除密码</button></div> : <div className="settings-inline-actions"><input type="password" value={password} onChange={(e)=>setPassword(e.target.value)} placeholder="至少 4 位"/><button className="secondary-button" disabled={password.length<4} onClick={()=>void onSetPassword(password)}>设置密码</button></div>}</fieldset>
  </div><footer className="settings-dialog__footer"><span>{saving ? '正在保存…' : '修改只应用到当前世界'}</span><div><button className="text-button" onClick={onClose}>取消</button><button className="primary-button" disabled={saving} onClick={()=>void onSave(draft)}>保存世界设置</button></div></footer></section></div>
}

export function WorldUnlockDialog({ worldName, onUnlock }: { worldName: string; onUnlock(password: string): Promise<void> }) { const [password,setPassword]=useState(''); const [error,setError]=useState<string>(); const [busy,setBusy]=useState(false); return <div className="modal-backdrop"><section className="world-unlock-dialog" role="dialog" aria-modal="true"><LockKey size={30}/><h2>{worldName} 已锁定</h2><p>输入当前世界的本地密码继续。</p><input autoFocus type="password" value={password} onChange={(e)=>setPassword(e.target.value)} onKeyDown={(e)=>{ if(e.key==='Enter' && password) void submit() }}/><button className="primary-button" disabled={!password||busy} onClick={()=>void submit()}>{busy?'正在解锁…':'解锁世界'}</button>{error?<p className="package-error">{error}</p>:null}</section></div>; async function submit(){setBusy(true);setError(undefined);try{await onUnlock(password)}catch(cause){setError(cause instanceof Error?cause.message:'解锁失败')}finally{setBusy(false)}} }
