import type { UiLocale } from '@dsh-cyber/contracts'
import { defineLocaleCatalogs } from './catalog-parity.js'
import { registerMessages } from './runtime.js'

const catalogs = defineLocaleCatalogs({
  'zh-CN': { permissionCurrent: "当前消息权限", permissionReadOnly: "只读访问", permissionReadOnlyDesc: "允许读取与搜索；修改文件需单独批准。", permissionWorkspaceWrite: "当前世界", permissionWorkspaceWriteDesc: "可读写当前世界的项目目录；越界操作需单独批准。", permissionFullAccess: "完全访问", permissionFullAccessDesc: "可读写当前系统账号可访问的文件并执行命令，不再请求工具审批。", artifactReady: "产物可用", artifactFailed: "产物登记失败", artifactCancelled: "产物登记已取消", artifactPending: "正在检查本轮产物…", retry: "重试", retrying: "正在重试…",
    currentWorld: '当前世界：', switchWorld: '切换世界', history: '查看历史消息', startChat: '开始与角色对话', startChatHint: '历史记录保留在当前世界；发送消息后角色才会开始处理。', composer: '发送消息给 {name}', approval: '请求批准', worldSettings: '世界管理', restoring: '正在恢复本地世界…', modelDefault: '恢复角色默认模型', modelLabel: '当前会话模型', modelTemporary: '会话临时选择',
    recruitRoleplay: '邀请角色', recruitNormal: '新增角色', recruitDesc: '从当前已安装或内置的角色模板中创建独立实例。新的模板请先到顶部「市场 → 角色」安装。', recruitSearch: '搜索模板名称、身份或职业…', recruitClearSearch: '清除搜索', recruitEmpty: '未搜索到匹配的角色模板。', recruitReading: '正在读取当前世界可用的角色模板与技能目录…', recruitNoCompatible: '当前世界还没有兼容模板。可以到顶部「市场 → 角色」安装，或通过创意工坊创建。', recruitExistingCount: '当前世界已有 {count} 名', recruitSelectPrompt: '请选择一份角色模板', recruitCreateForWorld: '将在当前世界创建独立角色：{name}', recruitCreating: '正在创建角色…', recruitReadingCatalog: '正在读取目录…', recruitCreateAnother: '再创建一名', recruitInvite: '邀请角色入场', recruitConfirmAdd: '确认新增', recruitRoleName: '角色名字（可选）', recruitDuplicateNameWarning: '当前世界已有同名角色，建议换一个名字以便区分。', recruitFullAccessConfirm: '我确认这个角色默认拥有完全访问', recruitFullAccessHint: '首次确认会持久保存；刷新、切换和重启后继续生效，直到你把角色改为较低权限。', recruitSkillsLegend: '角色技能', recruitNoSkills: '该角色模板未请求角色技能', recruitCapabilitiesLegend: '底层能力（按需批准）', recruitNoCapabilities: '该角色模板未请求额外底层能力', recruitNotice: '当前蓝图请求的安全工作方法默认勾选，可在创建前取消；需要外部连接或产生副作用的角色技能不会默认放行，执行时仍经过审批策略。底层能力继续按最小权限选择。', cancel: '取消',
    traceTitle: '世界轨迹', traceSubtitle: '可读的判断摘要、工具调度与实际用量', traceRefresh: '刷新世界轨迹', traceCount: '{count} 条轨迹', traceNoTokens: 'Token 暂无返回', traceLiveUpdate: '实时更新', traceActorStats: '按角色统计 Token', traceUnknownActor: '未知角色', traceLoadMore: '加载更早轨迹', traceLoading: '正在加载…',
    traceViews: '轨迹视图', traceViewTrace: '轨迹', traceViewContext: '上下文',
    groupCurrentWorld: '当前世界', groupTitle: '创建群聊', groupSubtitle: '选择至少两名角色，创建后立即出现在左侧会话列表。', groupSearch: '搜索角色或职责', groupName: '群聊名称', groupNamePlaceholder: '可选，默认使用成员名称', groupMode: '协作模式', groupModeDiscussion: '讨论', groupModeDiscussionDesc: '默认由所有成员参与多轮讨论。', groupModeTask: '协作', groupModeTaskDesc: '按角色和技能分配步骤，执行细节进入轨迹。', groupSelectedCount: '已选择 {count} 人', groupCreating: '正在创建…', groupCreateSubmit: '创建群聊',
    marketTitle: '扩展市场', marketSubtitle: '先选择世界，再发现角色与插件。所有内容经过完整性校验和事务安装。', marketTabTheme: '世界', marketTabThemeDesc: '选择完整场景皮肤、空间设定和起始角色，创建彼此独立的新世界。', marketTabTalent: '角色', marketTabTalentDesc: '安装不同世界观与专长的角色模板，再把角色招募到兼容世界。', marketTabPlugin: '插件', marketTabPluginDesc: '先安装到本地包库，再为需要的世界单独启用；每次安装都可审阅、回滚。', marketTabSkin: '皮肤', marketTabSkinDesc: '安装完整的场景皮肤；安装后才会出现在世界皮肤下拉，默认皮肤始终可用。', marketSearchPlaceholder: '搜索{category}、发布者或能力', marketSearchSubmit: '搜索', marketExtensionCount: '{count} 个扩展', marketCheckingLocal: '正在校验本地市场目录…', marketEmpty: '没有匹配的扩展', marketEmptyDesc: '可以修改关键词，或使用下方“本地导入”安装自定义包。', marketManualToggleOpen: '收起本地导入', marketManualToggleClose: '本地导入自定义包',
  },
  'zh-TW': { permissionCurrent: "目前訊息權限", permissionReadOnly: "唯讀", permissionReadOnlyDesc: "允許讀取與搜尋；修改檔案需個別核准。", permissionWorkspaceWrite: "目前專案", permissionWorkspaceWriteDesc: "可讀寫目前世界的專案目錄；越界操作需個別核准。", permissionFullAccess: "全域", permissionFullAccessDesc: "可讀寫目前系統帳號能存取的檔案並執行命令，不再要求工具核准。", artifactReady: "產物可用", artifactFailed: "產物登記失敗", artifactCancelled: "產物登記已取消", artifactPending: "正在檢查本輪產物…", retry: "重試", retrying: "正在重試…",
    currentWorld: '目前世界：', switchWorld: '切換世界', history: '歷史訊息', startChat: '開始與角色對話', startChatHint: '歷史記錄保留在目前世界；傳送訊息後角色才會開始處理。', composer: '傳送訊息給 {name}', approval: '請求核准', worldSettings: '世界管理', restoring: '正在恢復本機世界…', modelDefault: '恢復角色預設模型', modelLabel: '目前會話模型', modelTemporary: '會話暫時選擇',
    recruitRoleplay: '邀請角色', recruitNormal: '新增角色', recruitDesc: '從目前已安裝或內建的角色範本中建立獨立實例。新的範本請先至頂部「市場 → 角色」安裝。', recruitSearch: '搜尋範本名稱、身分或職業…', recruitClearSearch: '清除搜尋', recruitEmpty: '未搜尋到相符的角色範本。', recruitReading: '正在讀取目前世界可用的角色範本與技能目錄…', recruitNoCompatible: '目前世界還沒有相容範本。可以至頂部「市場 → 角色」安裝，或透過創意工坊建立。', recruitExistingCount: '目前世界已有 {count} 名', recruitSelectPrompt: '請選擇一份角色範本', recruitCreateForWorld: '將在目前世界建立獨立角色：{name}', recruitCreating: '正在建立角色…', recruitReadingCatalog: '正在讀取目錄…', recruitCreateAnother: '再建立一名', recruitInvite: '邀請角色入場', recruitConfirmAdd: '確認新增', recruitRoleName: '角色名字（可選）', recruitDuplicateNameWarning: '目前世界已有同名角色，建議更換名稱以便區分。', recruitFullAccessConfirm: '我確認這個角色預設擁有完全存取', recruitFullAccessHint: '首次確認會持久保存；重新整理、切換和重啟後繼續生效，直到你把角色改為較低權限。', recruitSkillsLegend: '角色技能', recruitNoSkills: '該角色範本未請求角色技能', recruitCapabilitiesLegend: '底層能力（按需核准）', recruitNoCapabilities: '該角色範本未請求額外底層能力', recruitNotice: '目前藍圖請求的安全工作方法預設勾選，可在建立前取消；需要外部連線或產生副作用的角色技能不會預設放行，執行時仍經過審批策略。底層能力繼續按最小權限選擇。', cancel: '取消',
    traceTitle: '世界軌跡', traceSubtitle: '可讀的判斷摘要、工具調度與實際用量', traceRefresh: '重新整理世界軌跡', traceCount: '{count} 條軌跡', traceNoTokens: 'Token 暫無返回', traceLiveUpdate: '即時更新', traceActorStats: '按角色統計 Token', traceUnknownActor: '未知角色', traceLoadMore: '載入更早軌跡', traceLoading: '載入中…',
    traceViews: '軌跡檢視', traceViewTrace: '軌跡', traceViewContext: '上下文',
    groupCurrentWorld: '目前世界', groupTitle: '建立群聊', groupSubtitle: '選擇至少兩名角色，建立後立即出現在左側會話清單。', groupSearch: '搜尋角色或職責', groupName: '群聊名稱', groupNamePlaceholder: '可選，預設使用成員名稱', groupMode: '協作模式', groupModeDiscussion: '討論', groupModeDiscussionDesc: '預設由所有成員參與多輪討論。', groupModeTask: '協作', groupModeTaskDesc: '按角色和技能分配步驟，執行細節進入軌跡。', groupSelectedCount: '已選擇 {count} 人', groupCreating: '正在建立…', groupCreateSubmit: '建立群聊',
    marketTitle: '擴充市場', marketSubtitle: '先選擇世界，再探索角色與外掛程式。所有內容經過完整性校驗和交易安裝。', marketTabTheme: '世界', marketTabThemeDesc: '選擇完整場景外觀、空間設定與起始角色，建立彼此獨立的新世界。', marketTabTalent: '角色', marketTabTalentDesc: '安裝不同世界觀與專長的角色範本，再將角色招募至相容世界。', marketTabPlugin: '外掛程式', marketTabPluginDesc: '先安裝至本機套件庫，再為需要的世界單獨啟用；每次安裝均可審閱、復原。', marketTabSkin: '外觀', marketTabSkinDesc: '安裝完整的場景外觀；安裝後才會出現在世界外觀選單，預設外觀始終可用。', marketSearchPlaceholder: '搜尋{category}、發布者或能力', marketSearchSubmit: '搜尋', marketExtensionCount: '{count} 個擴充', marketCheckingLocal: '正在校驗本機市場目錄…', marketEmpty: '沒有符合的擴充', marketEmptyDesc: '可以修改關鍵字，或使用下方「本機匯入」安裝自訂套件。', marketManualToggleOpen: '收起本機匯入', marketManualToggleClose: '本機匯入自訂套件',
  },
  'en-US': { permissionCurrent: "Message permissions", permissionReadOnly: "Read-only", permissionReadOnlyDesc: "Read and search; file changes require separate approval.", permissionWorkspaceWrite: "Current project", permissionWorkspaceWriteDesc: "Read and write in this world’s project directory; operations outside it require approval.", permissionFullAccess: "Global", permissionFullAccessDesc: "Read and write files accessible to this system account and run commands without tool approval.", artifactReady: "Artifact ready", artifactFailed: "Artifact registration failed", artifactCancelled: "Artifact registration cancelled", artifactPending: "Checking this turn for artifacts…", retry: "Retry", retrying: "Retrying…",
    currentWorld: 'Current world:', switchWorld: 'Switch world', history: 'Message history', startChat: 'Start a conversation', startChatHint: 'History stays in this world. The role starts working after you send a message.', composer: 'Message {name}', approval: 'Request approval', worldSettings: 'World Management', restoring: 'Restoring local worlds…', modelDefault: 'Use role default model', modelLabel: 'Conversation model', modelTemporary: 'Conversation override',
    recruitRoleplay: 'Invite Character', recruitNormal: 'Add Character', recruitDesc: 'Create an independent instance from installed or built-in templates. Install new templates in Market → Characters.', recruitSearch: 'Search templates by name, title, or role…', recruitClearSearch: 'Clear search', recruitEmpty: 'No matching character templates found.', recruitReading: 'Loading available character templates and skills…', recruitNoCompatible: 'No compatible templates found in this world. Install via Market → Characters or create in Workshop.', recruitExistingCount: '{count} already in this world', recruitSelectPrompt: 'Select a character template', recruitCreateForWorld: 'Will create instance in this world: {name}', recruitCreating: 'Creating character…', recruitReadingCatalog: 'Loading catalog…', recruitCreateAnother: 'Create Another', recruitInvite: 'Invite Character', recruitConfirmAdd: 'Confirm Add', recruitRoleName: 'Character Name (Optional)', recruitDuplicateNameWarning: 'A character with this name already exists in this world. Consider renaming.', recruitFullAccessConfirm: 'I confirm this character has full system access by default', recruitFullAccessHint: 'Persisted on confirmation; stays active across restarts until reduced.', recruitSkillsLegend: 'Role Skills', recruitNoSkills: 'No role skills requested by this template', recruitCapabilitiesLegend: 'Underlying Capabilities', recruitNoCapabilities: 'No extra capabilities requested', recruitNotice: 'Safe capabilities are pre-selected. External network and shell actions undergo approval gates.', cancel: 'Cancel',
    traceTitle: 'World Trace', traceSubtitle: 'Readable judgment summaries, tool scheduling, and token consumption', traceRefresh: 'Refresh World Trace', traceCount: '{count} traces', traceNoTokens: 'No tokens reported', traceLiveUpdate: 'Live updating', traceActorStats: 'Token breakdown by role', traceUnknownActor: 'Unknown Character', traceLoadMore: 'Load earlier traces', traceLoading: 'Loading…',
    traceViews: 'Trace views', traceViewTrace: 'Trace', traceViewContext: 'Context',
    groupCurrentWorld: 'Current World', groupTitle: 'Create Group Chat', groupSubtitle: 'Select at least two characters. The group appears immediately in your conversation list.', groupSearch: 'Search roles or responsibilities', groupName: 'Group Name', groupNamePlaceholder: 'Optional, defaults to member names', groupMode: 'Collaboration Mode', groupModeDiscussion: 'Discussion', groupModeDiscussionDesc: 'All members participate in multi-turn discussion by default.', groupModeTask: 'Task Team', groupModeTaskDesc: 'Assign steps by role and skills; execution details enter trace.', groupSelectedCount: '{count} selected', groupCreating: 'Creating…', groupCreateSubmit: 'Create Group',
    marketTitle: 'Extension Market', marketSubtitle: 'Choose worlds first, then discover characters and plugins. All content verified for integrity.', marketTabTheme: 'Worlds', marketTabThemeDesc: 'Pick scenic themes, rules, and starting roles to spawn independent worlds.', marketTabTalent: 'Characters', marketTabTalentDesc: 'Install character templates and recruit them into compatible worlds.', marketTabPlugin: 'Plugins', marketTabPluginDesc: 'Install to local catalog, then enable per-world with review and rollback.', marketTabSkin: 'Themes', marketTabSkinDesc: 'Install scenic themes; they appear in the theme menu upon installation.', marketSearchPlaceholder: 'Search {category}, publisher, or capability', marketSearchSubmit: 'Search', marketExtensionCount: '{count} extensions', marketCheckingLocal: 'Verifying local catalog…', marketEmpty: 'No matching extensions', marketEmptyDesc: 'Try adjusting keywords, or import custom packages below.', marketManualToggleOpen: 'Collapse Local Import', marketManualToggleClose: 'Import Custom Package',
  },
  'ja-JP': { permissionCurrent: "現在の権限", permissionReadOnly: "読み取り専用", permissionReadOnlyDesc: "読み取りと検索が可能。ファイル変更には個別の承認が必要です。", permissionWorkspaceWrite: "現在のプロジェクト", permissionWorkspaceWriteDesc: "このワールドのプロジェクト内で読み書き可能。範囲外の操作には承認が必要です。", permissionFullAccess: "グローバル", permissionFullAccessDesc: "システムアカウントでアクセス可能なファイルの読み書きとコマンド実行を、ツール承認なしで行います。", artifactReady: "成果物利用可能", artifactFailed: "成果物の登録に失敗", artifactCancelled: "成果物の登録がキャンセルされました", artifactPending: "このターンの成果物を確認中…", retry: "再試行", retrying: "再試行中…",
    currentWorld: '現在のワールド：', switchWorld: 'ワールドを切り替え', history: 'メッセージ履歴', startChat: '役割との会話を開始', startChatHint: '履歴はこのワールドに保存されます。メッセージ送信後に役割が処理を開始します。', composer: '{name} にメッセージを送信', approval: '承認を依頼', worldSettings: 'ワールド設定', restoring: 'ローカルワールドを復元中…', modelDefault: '役割の既定モデルに戻す', modelLabel: '会話モデル', modelTemporary: '会話の一時選択',
    recruitRoleplay: 'キャラクターを招待', recruitNormal: 'キャラクター追加', recruitDesc: '導入済みまたは組み込みのテンプレートから独立インスタンスを作成します。', recruitSearch: 'テンプレート名、肩書、役割で検索…', recruitClearSearch: '検索クリア', recruitEmpty: '一致するテンプレートが見つかりません。', recruitReading: 'テンプレートとスキル一覧を読み込み中…', recruitNoCompatible: '互換性のあるテンプレートがありません。', recruitExistingCount: '現在 {count} 名在籍', recruitSelectPrompt: 'テンプレートを選択してください', recruitCreateForWorld: '作成対象: {name}', recruitCreating: '作成中…', recruitReadingCatalog: '読み込み中…', recruitCreateAnother: 'もう 1 名追加', recruitInvite: '招待する', recruitConfirmAdd: '追加を確定', recruitRoleName: 'キャラクター名（任意）', recruitDuplicateNameWarning: '同名のキャラクターが既に存在します。', recruitFullAccessConfirm: '完全アクセス権を付与することを確認します', recruitFullAccessHint: '権限を変更するまで再起動後も有効です。', recruitSkillsLegend: '役割スキル', recruitNoSkills: 'スキル要求はありません', recruitCapabilitiesLegend: '基本権限', recruitNoCapabilities: '追加権限要求はありません', recruitNotice: '安全な機能のみ既定で選択されています。', cancel: 'キャンセル',
    traceTitle: 'ワールド軌跡', traceSubtitle: '思考要約、ツール実行とトークン使用量', traceRefresh: '軌跡を更新', traceCount: '{count} 件の軌跡', traceNoTokens: 'トークン未返却', traceLiveUpdate: 'リアルタイム更新', traceActorStats: '役割別トークン', traceUnknownActor: '不明なキャラクター',
    // Not translated for this locale yet; the runtime falls back to en-US.
    traceLoadMore: null, traceLoading: null, traceViews: null, traceViewTrace: null, traceViewContext: null, groupCurrentWorld: null, groupTitle: null, groupSubtitle: null, groupSearch: null, groupName: null, groupNamePlaceholder: null, groupMode: null, groupModeDiscussion: null, groupModeDiscussionDesc: null, groupModeTask: null, groupModeTaskDesc: null, groupSelectedCount: null, groupCreating: null, groupCreateSubmit: null, marketTitle: null, marketSubtitle: null, marketTabTheme: null, marketTabThemeDesc: null, marketTabTalent: null, marketTabTalentDesc: null, marketTabPlugin: null, marketTabPluginDesc: null, marketTabSkin: null, marketTabSkinDesc: null, marketSearchPlaceholder: null, marketSearchSubmit: null, marketExtensionCount: null, marketCheckingLocal: null, marketEmpty: null, marketEmptyDesc: null, marketManualToggleOpen: null, marketManualToggleClose: null,
  },
  'ko-KR': { permissionCurrent: "현재 메시지 권한", permissionReadOnly: "읽기 전용", permissionReadOnlyDesc: "읽기와 검색을 허용합니다. 파일 변경에는 별도 승인이 필요합니다.", permissionWorkspaceWrite: "현재 프로젝트", permissionWorkspaceWriteDesc: "현재 세계의 프로젝트 폴더에서 읽고 씁니다. 범위 밖 작업에는 승인이 필요합니다.", permissionFullAccess: "전역", permissionFullAccessDesc: "시스템 계정이 접근할 수 있는 파일을 읽고 쓰며 도구 승인 없이 명령을 실행합니다.", artifactReady: "산출물 준비됨", artifactFailed: "산출물 등록 실패", artifactCancelled: "산출물 등록 취소됨", artifactPending: "이번 응답의 산출물 확인 중…", retry: "다시 시도", retrying: "다시 시도 중…",
    currentWorld: '현재 세계:', switchWorld: '세계 전환', history: '메시지 기록', startChat: '역할과 대화 시작', startChatHint: '기록은 현재 세계에 보관되며 메시지를 보내면 역할이 작업을 시작합니다.', composer: '{name}에게 메시지 보내기', approval: '승인 요청', worldSettings: '세계 설정', restoring: '로컬 세계 복원 중…', modelDefault: '역할 기본 모델 사용', modelLabel: '대화 모델', modelTemporary: '대화 임시 선택',
    recruitRoleplay: '캐릭터 초대', recruitNormal: '역할 추가', recruitDesc: '템플릿에서 독립 인스턴스를 생성합니다.', recruitSearch: '템플릿 이름, 직업 검색…', recruitClearSearch: '검색 지우기', recruitEmpty: '일치하는 템플릿이 없습니다.', recruitReading: '템플릿 목록 불러오는 중…', recruitNoCompatible: '호환되는 템플릿이 없습니다.', recruitExistingCount: '현재 {count}명 존재', recruitSelectPrompt: '템플릿을 선택하세요', recruitCreateForWorld: '생성 대상: {name}', recruitCreating: '생성 중…', recruitReadingCatalog: '로딩 중…', recruitCreateAnother: '추가 생성', recruitInvite: '초대하기', recruitConfirmAdd: '추가 확정', recruitRoleName: '캐릭터 이름(선택)', recruitDuplicateNameWarning: '이미 같은 이름이 존재합니다.', recruitFullAccessConfirm: '전체 접근 권한 부여 확인', recruitFullAccessHint: '권한을 변경할 때까지 유지됩니다.', recruitSkillsLegend: '역할 스킬', recruitNoSkills: '요청된 스킬 없음', recruitCapabilitiesLegend: '기본 권한', recruitNoCapabilities: '추가 권한 요청 없음', recruitNotice: '안전한 기능만 기본 선택됩니다.', cancel: '취소',
    traceTitle: '세계 궤적', traceSubtitle: '판단 요약, 도구 호출 및 토큰 사용량', traceRefresh: '새로고침', traceCount: '{count}개 궤적', traceNoTokens: '토큰 없음', traceLiveUpdate: '실시간 업데이트', traceActorStats: '역할별 토큰', traceUnknownActor: '알 수 없는 캐릭터',
    // Not translated for this locale yet; the runtime falls back to en-US.
    traceLoadMore: null, traceLoading: null, traceViews: null, traceViewTrace: null, traceViewContext: null, groupCurrentWorld: null, groupTitle: null, groupSubtitle: null, groupSearch: null, groupName: null, groupNamePlaceholder: null, groupMode: null, groupModeDiscussion: null, groupModeDiscussionDesc: null, groupModeTask: null, groupModeTaskDesc: null, groupSelectedCount: null, groupCreating: null, groupCreateSubmit: null, marketTitle: null, marketSubtitle: null, marketTabTheme: null, marketTabThemeDesc: null, marketTabTalent: null, marketTabTalentDesc: null, marketTabPlugin: null, marketTabPluginDesc: null, marketTabSkin: null, marketTabSkinDesc: null, marketSearchPlaceholder: null, marketSearchSubmit: null, marketExtensionCount: null, marketCheckingLocal: null, marketEmpty: null, marketEmptyDesc: null, marketManualToggleOpen: null, marketManualToggleClose: null,
  },
  'es-ES': { permissionCurrent: "Permisos del mensaje", permissionReadOnly: "Solo lectura", permissionReadOnlyDesc: "Leer y buscar; los cambios en archivos requieren aprobación.", permissionWorkspaceWrite: "Proyecto actual", permissionWorkspaceWriteDesc: "Leer y escribir en el proyecto de este mundo; las operaciones externas requieren aprobación.", permissionFullAccess: "Global", permissionFullAccessDesc: "Leer y escribir archivos accesibles a esta cuenta y ejecutar comandos sin aprobación de herramientas.", artifactReady: "Artefacto listo", artifactFailed: "Error al registrar el artefacto", artifactCancelled: "Registro cancelado", artifactPending: "Comprobando artefactos de este turno…", retry: "Reintentar", retrying: "Reintentando…",
    currentWorld: 'Mundo actual:', switchWorld: 'Cambiar de mundo', history: 'Historial de mensajes', startChat: 'Iniciar una conversación', startChatHint: 'El historial permanece en este mundo. El rol empieza a trabajar cuando envías un mensaje.', composer: 'Enviar mensaje a {name}', approval: 'Solicitar aprobación', worldSettings: 'Configuración del mundo', restoring: 'Restaurando mundos locales…', modelDefault: 'Usar el modelo predeterminado del rol', modelLabel: 'Modelo de conversación', modelTemporary: 'Selección temporal',
    recruitRoleplay: 'Invitar Personaje', recruitNormal: 'Añadir Personaje', recruitDesc: 'Crea instancias a partir de plantillas.', recruitSearch: 'Buscar plantillas…', recruitClearSearch: 'Limpiar búsqueda', recruitEmpty: 'No hay plantillas coincidentes.', recruitReading: 'Cargando plantillas…', recruitNoCompatible: 'No hay plantillas compatibles.', recruitExistingCount: '{count} ya en este mundo', recruitSelectPrompt: 'Selecciona una plantilla', recruitCreateForWorld: 'Crear en este mundo: {name}', recruitCreating: 'Creando…', recruitReadingCatalog: 'Cargando…', recruitCreateAnother: 'Crear otro', recruitInvite: 'Invitar', recruitConfirmAdd: 'Confirmar', recruitRoleName: 'Nombre (opcional)', recruitDuplicateNameWarning: 'Ya existe un personaje con este nombre.', recruitFullAccessConfirm: 'Confirmo acceso completo', recruitFullAccessHint: 'Permanece activo hasta reducirse.', recruitSkillsLegend: 'Habilidades', recruitNoSkills: 'Sin habilidades solicitadas', recruitCapabilitiesLegend: 'Capacidades', recruitNoCapabilities: 'Sin capacidades adicionales', recruitNotice: 'Capacidades seguras preseleccionadas.', cancel: 'Cancelar',
    traceTitle: 'Trayectoria del Mundo', traceSubtitle: 'Resúmenes y consumo de tokens', traceRefresh: 'Actualizar', traceCount: '{count} registros', traceNoTokens: 'Sin tokens', traceLiveUpdate: 'En vivo', traceActorStats: 'Tokens por rol', traceUnknownActor: 'Desconocido',
    // Not translated for this locale yet; the runtime falls back to en-US.
    traceLoadMore: null, traceLoading: null, traceViews: null, traceViewTrace: null, traceViewContext: null, groupCurrentWorld: null, groupTitle: null, groupSubtitle: null, groupSearch: null, groupName: null, groupNamePlaceholder: null, groupMode: null, groupModeDiscussion: null, groupModeDiscussionDesc: null, groupModeTask: null, groupModeTaskDesc: null, groupSelectedCount: null, groupCreating: null, groupCreateSubmit: null, marketTitle: null, marketSubtitle: null, marketTabTheme: null, marketTabThemeDesc: null, marketTabTalent: null, marketTabTalentDesc: null, marketTabPlugin: null, marketTabPluginDesc: null, marketTabSkin: null, marketTabSkinDesc: null, marketSearchPlaceholder: null, marketSearchSubmit: null, marketExtensionCount: null, marketCheckingLocal: null, marketEmpty: null, marketEmptyDesc: null, marketManualToggleOpen: null, marketManualToggleClose: null,
  },
  'fr-FR': { permissionCurrent: "Permissions du message", permissionReadOnly: "Lecture seule", permissionReadOnlyDesc: "Lire et rechercher ; modifier des fichiers nécessite une approbation.", permissionWorkspaceWrite: "Projet actuel", permissionWorkspaceWriteDesc: "Lire et écrire dans le projet de ce monde ; les opérations externes nécessitent une approbation.", permissionFullAccess: "Global", permissionFullAccessDesc: "Lire et écrire les fichiers accessibles à ce compte et exécuter des commandes sans approbation des outils.", artifactReady: "Artefact prêt", artifactFailed: "Échec de l’enregistrement de l’artefact", artifactCancelled: "Enregistrement annulé", artifactPending: "Vérification des artefacts de ce tour…", retry: "Réessayer", retrying: "Nouvelle tentative…",
    currentWorld: 'Monde actuel :', switchWorld: 'Changer de monde', history: 'Historique des messages', startChat: 'Démarrer une conversation', startChatHint: 'L’historique reste dans ce monde. Le rôle commence à travailler après l’envoi du message.', composer: 'Envoyer un message à {name}', approval: 'Demander une approbation', worldSettings: 'Paramètres du monde', restoring: 'Restauration des mondes locaux…', modelDefault: 'Utiliser le modèle par défaut du rôle', modelLabel: 'Modèle de conversation', modelTemporary: 'Sélection temporaire',
    recruitRoleplay: 'Inviter le personnage', recruitNormal: 'Ajouter un personnage', recruitDesc: 'Créer une instance depuis un modèle.', recruitSearch: 'Rechercher un modèle…', recruitClearSearch: 'Effacer', recruitEmpty: 'Aucun modèle correspondant.', recruitReading: 'Chargement des modèles…', recruitNoCompatible: 'Aucun modèle compatible.', recruitExistingCount: '{count} déjà présents', recruitSelectPrompt: 'Sélectionner un modèle', recruitCreateForWorld: 'Créer dans ce monde : {name}', recruitCreating: 'Création…', recruitReadingCatalog: 'Chargement…', recruitCreateAnother: 'En créer un autre', recruitInvite: 'Inviter', recruitConfirmAdd: 'Confirmer', recruitRoleName: 'Nom (optionnel)', recruitDuplicateNameWarning: 'Un personnage porte déjà ce nom.', recruitFullAccessConfirm: 'Je confirme l’accès complet', recruitFullAccessHint: 'Reste actif jusqu’à modification.', recruitSkillsLegend: 'Compétences', recruitNoSkills: 'Aucune compétence demandée', recruitCapabilitiesLegend: 'Capacités', recruitNoCapabilities: 'Aucune capacité demandée', recruitNotice: 'Capacités sécurisées sélectionnées.', cancel: 'Annuler',
    traceTitle: 'Trajectoire du monde', traceSubtitle: 'Résumés et consommation de tokens', traceRefresh: 'Actualiser', traceCount: '{count} entrées', traceNoTokens: 'Aucun token', traceLiveUpdate: 'En direct', traceActorStats: 'Tokens par rôle', traceUnknownActor: 'Inconnu',
    // Not translated for this locale yet; the runtime falls back to en-US.
    traceLoadMore: null, traceLoading: null, traceViews: null, traceViewTrace: null, traceViewContext: null, groupCurrentWorld: null, groupTitle: null, groupSubtitle: null, groupSearch: null, groupName: null, groupNamePlaceholder: null, groupMode: null, groupModeDiscussion: null, groupModeDiscussionDesc: null, groupModeTask: null, groupModeTaskDesc: null, groupSelectedCount: null, groupCreating: null, groupCreateSubmit: null, marketTitle: null, marketSubtitle: null, marketTabTheme: null, marketTabThemeDesc: null, marketTabTalent: null, marketTabTalentDesc: null, marketTabPlugin: null, marketTabPluginDesc: null, marketTabSkin: null, marketTabSkinDesc: null, marketSearchPlaceholder: null, marketSearchSubmit: null, marketExtensionCount: null, marketCheckingLocal: null, marketEmpty: null, marketEmptyDesc: null, marketManualToggleOpen: null, marketManualToggleClose: null,
  },
  'de-DE': { permissionCurrent: "Nachrichtenberechtigungen", permissionReadOnly: "Nur lesen", permissionReadOnlyDesc: "Lesen und suchen; Dateiänderungen erfordern eine Genehmigung.", permissionWorkspaceWrite: "Aktuelles Projekt", permissionWorkspaceWriteDesc: "Im Projekt dieser Welt lesen und schreiben; externe Vorgänge erfordern eine Genehmigung.", permissionFullAccess: "Global", permissionFullAccessDesc: "Für dieses Systemkonto zugängliche Dateien lesen und schreiben sowie Befehle ohne Werkzeugfreigabe ausführen.", artifactReady: "Artefakt bereit", artifactFailed: "Artefaktregistrierung fehlgeschlagen", artifactCancelled: "Registrierung abgebrochen", artifactPending: "Artefakte dieses Durchlaufs werden geprüft…", retry: "Wiederholen", retrying: "Wird wiederholt…",
    currentWorld: 'Aktuelle Welt:', switchWorld: 'Welt wechseln', history: 'Nachrichtenverlauf', startChat: 'Unterhaltung beginnen', startChatHint: 'Der Verlauf bleibt in dieser Welt. Die Rolle beginnt nach dem Senden einer Nachricht.', composer: 'Nachricht an {name}', approval: 'Genehmigung anfordern', worldSettings: 'Welteinstellungen', restoring: 'Lokale Welten werden wiederhergestellt…', modelDefault: 'Standardmodell der Rolle verwenden', modelLabel: 'Unterhaltungsmodell', modelTemporary: 'Temporäre Auswahl',
    recruitRoleplay: 'Charakter einladen', recruitNormal: 'Charakter hinzufügen', recruitDesc: 'Instanz aus Vorlage erstellen.', recruitSearch: 'Vorlagen suchen…', recruitClearSearch: 'Suche leeren', recruitEmpty: 'Keine passenden Vorlagen.', recruitReading: 'Vorlagen werden geladen…', recruitNoCompatible: 'Keine kompatiblen Vorlagen.', recruitExistingCount: '{count} bereits vorhanden', recruitSelectPrompt: 'Vorlage auswählen', recruitCreateForWorld: 'Wird erstellt: {name}', recruitCreating: 'Wird erstellt…', recruitReadingCatalog: 'Wird geladen…', recruitCreateAnother: 'Weiteren erstellen', recruitInvite: 'Einladen', recruitConfirmAdd: 'Bestätigen', recruitRoleName: 'Name (optional)', recruitDuplicateNameWarning: 'Name bereits vergeben.', recruitFullAccessConfirm: 'Vollzugriff bestätigen', recruitFullAccessHint: 'Bleibt bis Änderung aktiv.', recruitSkillsLegend: 'Fähigkeiten', recruitNoSkills: 'Keine Fähigkeiten angefordert', recruitCapabilitiesLegend: 'Berechtigungen', recruitNoCapabilities: 'Keine weiteren Berechtigungen', recruitNotice: 'Sichere Funktionen vorausgewählt.', cancel: 'Abbrechen',
    traceTitle: 'Welt-Spur', traceSubtitle: 'Zusammenfassungen und Token-Verbrauch', traceRefresh: 'Aktualisieren', traceCount: '{count} Einträge', traceNoTokens: 'Keine Tokens', traceLiveUpdate: 'Live', traceActorStats: 'Tokens nach Rolle', traceUnknownActor: 'Unbekannt',
    // Not translated for this locale yet; the runtime falls back to en-US.
    traceLoadMore: null, traceLoading: null, traceViews: null, traceViewTrace: null, traceViewContext: null, groupCurrentWorld: null, groupTitle: null, groupSubtitle: null, groupSearch: null, groupName: null, groupNamePlaceholder: null, groupMode: null, groupModeDiscussion: null, groupModeDiscussionDesc: null, groupModeTask: null, groupModeTaskDesc: null, groupSelectedCount: null, groupCreating: null, groupCreateSubmit: null, marketTitle: null, marketSubtitle: null, marketTabTheme: null, marketTabThemeDesc: null, marketTabTalent: null, marketTabTalentDesc: null, marketTabPlugin: null, marketTabPluginDesc: null, marketTabSkin: null, marketTabSkinDesc: null, marketSearchPlaceholder: null, marketSearchSubmit: null, marketExtensionCount: null, marketCheckingLocal: null, marketEmpty: null, marketEmptyDesc: null, marketManualToggleOpen: null, marketManualToggleClose: null,
  },
  'pt-BR': { permissionCurrent: "Permissões da mensagem", permissionReadOnly: "Somente leitura", permissionReadOnlyDesc: "Ler e pesquisar; alterações em arquivos exigem aprovação.", permissionWorkspaceWrite: "Projeto atual", permissionWorkspaceWriteDesc: "Ler e escrever no projeto deste mundo; operações externas exigem aprovação.", permissionFullAccess: "Global", permissionFullAccessDesc: "Ler e escrever arquivos acessíveis à conta do sistema e executar comandos sem aprovação de ferramentas.", artifactReady: "Artefato pronto", artifactFailed: "Falha ao registrar artefato", artifactCancelled: "Registro cancelado", artifactPending: "Verificando artefatos desta execução…", retry: "Tentar novamente", retrying: "Tentando novamente…",
    currentWorld: 'Mundo atual:', switchWorld: 'Trocar de mundo', history: 'Histórico de mensagens', startChat: 'Iniciar uma conversa', startChatHint: 'O histórico permanece neste mundo. O papel começa a trabalhar após o envio da mensagem.', composer: 'Enviar mensagem para {name}', approval: 'Solicitar aprovação', worldSettings: 'Configurações do mundo', restoring: 'Restaurando mundos locais…', modelDefault: 'Usar o modelo padrão do papel', modelLabel: 'Modelo da conversa', modelTemporary: 'Seleção temporária',
    recruitRoleplay: 'Convidar Personagem', recruitNormal: 'Adicionar Personagem', recruitDesc: 'Criar instância a partir de modelos.', recruitSearch: 'Pesquisar modelos…', recruitClearSearch: 'Limpar', recruitEmpty: 'Nenhum modelo encontrado.', recruitReading: 'Carregando modelos…', recruitNoCompatible: 'Nenhum modelo compatível.', recruitExistingCount: '{count} já presentes', recruitSelectPrompt: 'Selecione um modelo', recruitCreateForWorld: 'Criar neste mundo: {name}', recruitCreating: 'Criando…', recruitReadingCatalog: 'Carregando…', recruitCreateAnother: 'Criar outro', recruitInvite: 'Convidar', recruitConfirmAdd: 'Confirmar', recruitRoleName: 'Nome (opcional)', recruitDuplicateNameWarning: 'Nome já existente.', recruitFullAccessConfirm: 'Confirmo acesso completo', recruitFullAccessHint: 'Permanece ativo até alteração.', recruitSkillsLegend: 'Habilidades', recruitNoSkills: 'Sem habilidades', recruitCapabilitiesLegend: 'Capacidades', recruitNoCapabilities: 'Sem capacidades extras', recruitNotice: 'Ações seguras pré-selecionadas.', cancel: 'Cancelar',
    traceTitle: 'Trajetória do Mundo', traceSubtitle: 'Resumos e uso de tokens', traceRefresh: 'Atualizar', traceCount: '{count} registros', traceNoTokens: 'Sem tokens', traceLiveUpdate: 'Ao vivo', traceActorStats: 'Tokens por papel', traceUnknownActor: 'Desconhecido',
    // Not translated for this locale yet; the runtime falls back to en-US.
    traceLoadMore: null, traceLoading: null, traceViews: null, traceViewTrace: null, traceViewContext: null, groupCurrentWorld: null, groupTitle: null, groupSubtitle: null, groupSearch: null, groupName: null, groupNamePlaceholder: null, groupMode: null, groupModeDiscussion: null, groupModeDiscussionDesc: null, groupModeTask: null, groupModeTaskDesc: null, groupSelectedCount: null, groupCreating: null, groupCreateSubmit: null, marketTitle: null, marketSubtitle: null, marketTabTheme: null, marketTabThemeDesc: null, marketTabTalent: null, marketTabTalentDesc: null, marketTabPlugin: null, marketTabPluginDesc: null, marketTabSkin: null, marketTabSkinDesc: null, marketSearchPlaceholder: null, marketSearchSubmit: null, marketExtensionCount: null, marketCheckingLocal: null, marketEmpty: null, marketEmptyDesc: null, marketManualToggleOpen: null, marketManualToggleClose: null,
  },
  'ru-RU': { permissionCurrent: "Права сообщения", permissionReadOnly: "Только чтение", permissionReadOnlyDesc: "Чтение и поиск; изменение файлов требует отдельного одобрения.", permissionWorkspaceWrite: "Текущий проект", permissionWorkspaceWriteDesc: "Чтение и запись в проекте этого мира; операции вне него требуют одобрения.", permissionFullAccess: "Глобально", permissionFullAccessDesc: "Чтение и запись доступных системной учётной записи файлов и выполнение команд без одобрения инструментов.", artifactReady: "Артефакт готов", artifactFailed: "Ошибка регистрации артефакта", artifactCancelled: "Регистрация отменена", artifactPending: "Проверка артефактов этого запуска…", retry: "Повторить", retrying: "Повторная попытка…",
    currentWorld: 'Текущий мир:', switchWorld: 'Сменить мир', history: 'История сообщений', startChat: 'Начать разговор', startChatHint: 'История хранится в этом мире. Роль начнёт работу после отправки сообщения.', composer: 'Сообщение для {name}', approval: 'Запросить одобрение', worldSettings: 'Настройки мира', restoring: 'Восстановление локальных миров…', modelDefault: 'Использовать стандартную модель роли', modelLabel: 'Модель разговора', modelTemporary: 'Временный выбор',
    recruitRoleplay: 'Пригласить персонажа', recruitNormal: 'Добавить персонажа', recruitDesc: 'Создать экземпляр из шаблона.', recruitSearch: 'Поиск шаблонов…', recruitClearSearch: 'Очистить', recruitEmpty: 'Шаблоны не найдены.', recruitReading: 'Загрузка шаблонов…', recruitNoCompatible: 'Нет совместимых шаблонов.', recruitExistingCount: '{count} уже в этом мире', recruitSelectPrompt: 'Выберите шаблон', recruitCreateForWorld: 'Будет создан: {name}', recruitCreating: 'Создание…', recruitReadingCatalog: 'Загрузка…', recruitCreateAnother: 'Создать ещё одного', recruitInvite: 'Пригласить', recruitConfirmAdd: 'Подтвердить', recruitRoleName: 'Имя (необязательно)', recruitDuplicateNameWarning: 'Персонаж с таким именем уже есть.', recruitFullAccessConfirm: 'Подтверждаю полный доступ', recruitFullAccessHint: 'Действует до изменения прав.', recruitSkillsLegend: 'Навыки роли', recruitNoSkills: 'Навыки не запрошены', recruitCapabilitiesLegend: 'Базовые права', recruitNoCapabilities: 'Доп. права не запрошены', recruitNotice: 'Безопасные методы выбраны по умолчанию.', cancel: 'Отмена',
    traceTitle: 'Траектория мира', traceSubtitle: 'Сводка и расход токенов', traceRefresh: 'Обновить', traceCount: '{count} записей', traceNoTokens: 'Токены не возвращены', traceLiveUpdate: 'В реальном времени', traceActorStats: 'Токены по ролям', traceUnknownActor: 'Неизвестный',
    // Not translated for this locale yet; the runtime falls back to en-US.
    traceLoadMore: null, traceLoading: null, traceViews: null, traceViewTrace: null, traceViewContext: null, groupCurrentWorld: null, groupTitle: null, groupSubtitle: null, groupSearch: null, groupName: null, groupNamePlaceholder: null, groupMode: null, groupModeDiscussion: null, groupModeDiscussionDesc: null, groupModeTask: null, groupModeTaskDesc: null, groupSelectedCount: null, groupCreating: null, groupCreateSubmit: null, marketTitle: null, marketSubtitle: null, marketTabTheme: null, marketTabThemeDesc: null, marketTabTalent: null, marketTabTalentDesc: null, marketTabPlugin: null, marketTabPluginDesc: null, marketTabSkin: null, marketTabSkinDesc: null, marketSearchPlaceholder: null, marketSearchSubmit: null, marketExtensionCount: null, marketCheckingLocal: null, marketEmpty: null, marketEmptyDesc: null, marketManualToggleOpen: null, marketManualToggleClose: null,
  },
  'ar-SA': { permissionCurrent: "أذونات الرسالة", permissionReadOnly: "للقراءة فقط", permissionReadOnlyDesc: "القراءة والبحث؛ تعديل الملفات يتطلب موافقة منفصلة.", permissionWorkspaceWrite: "المشروع الحالي", permissionWorkspaceWriteDesc: "القراءة والكتابة في مشروع هذا العالم؛ العمليات خارجه تتطلب موافقة.", permissionFullAccess: "عام", permissionFullAccessDesc: "قراءة وكتابة الملفات المتاحة لحساب النظام وتنفيذ الأوامر دون طلب موافقة الأدوات.", artifactReady: "النتاج جاهز", artifactFailed: "فشل تسجيل النتاج", artifactCancelled: "تم إلغاء التسجيل", artifactPending: "جارٍ التحقق من نتاج هذه الجولة…", retry: "إعادة المحاولة", retrying: "جاري إعادة المحاولة…",
    currentWorld: 'العالم الحالي:', switchWorld: 'تبديل العالم', history: 'سجل الرسائل', startChat: 'بدء محادثة', startChatHint: 'يبقى السجل في هذا العالم، ويبدأ الدور العمل بعد إرسال رسالة.', composer: 'إرسال رسالة إلى {name}', approval: 'طلب الموافقة', worldSettings: 'إعدادات العالم', restoring: 'جارٍ استعادة العوالم المحلية…', modelDefault: 'استخدام النموذج الافتراضي للدور', modelLabel: 'نموذج المحادثة', modelTemporary: 'اختيار مؤقت للمحادثة' ,
    recruitRoleplay: 'دعوة شخصية', recruitNormal: 'إضافة شخصية', recruitDesc: 'إنشاء نسخة مستقلة من القوالب.', recruitSearch: 'بحث عن القوالب…', recruitClearSearch: 'مسح', recruitEmpty: 'لا توجد قوالب مطابقة.', recruitReading: 'جارٍ تحميل القوالب…', recruitNoCompatible: 'لا توجد قوالب متوافقة.', recruitExistingCount: '{count} موجودون بالفعل', recruitSelectPrompt: 'اختر قالباً', recruitCreateForWorld: 'سيتم الإنشاء: {name}', recruitCreating: 'جارٍ الإنشاء…', recruitReadingCatalog: 'تحميل…', recruitCreateAnother: 'إنشاء آخر', recruitInvite: 'دعوة', recruitConfirmAdd: 'تأكيد', recruitRoleName: 'الاسم (اختياري)', recruitDuplicateNameWarning: 'الاسم مستخدم بالفعل.', recruitFullAccessConfirm: 'أؤكد الوصول الكامل', recruitFullAccessHint: 'يظل سارياً حتى التعديل.', recruitSkillsLegend: 'مهارات الدور', recruitNoSkills: 'لا توجد مهارات مطلوبة', recruitCapabilitiesLegend: 'القدرات', recruitNoCapabilities: 'لا توجد قدرات إضافية', recruitNotice: 'تم تحديد الوظائف الآمنة تلقائياً.', cancel: 'إلغاء',
    traceTitle: 'مسار العالم', traceSubtitle: 'ملخصات القرارات واستهلاك الرموز', traceRefresh: 'تحديث', traceCount: '{count} مسار', traceNoTokens: 'لا توجد رموز', traceLiveUpdate: 'تحديث مباشر', traceActorStats: 'الرموز حسب الشخصية', traceUnknownActor: 'شخصية مجهولة',
    // Not translated for this locale yet; the runtime falls back to en-US.
    traceLoadMore: null, traceLoading: null, traceViews: null, traceViewTrace: null, traceViewContext: null, groupCurrentWorld: null, groupTitle: null, groupSubtitle: null, groupSearch: null, groupName: null, groupNamePlaceholder: null, groupMode: null, groupModeDiscussion: null, groupModeDiscussionDesc: null, groupModeTask: null, groupModeTaskDesc: null, groupSelectedCount: null, groupCreating: null, groupCreateSubmit: null, marketTitle: null, marketSubtitle: null, marketTabTheme: null, marketTabThemeDesc: null, marketTabTalent: null, marketTabTalentDesc: null, marketTabPlugin: null, marketTabPluginDesc: null, marketTabSkin: null, marketTabSkinDesc: null, marketSearchPlaceholder: null, marketSearchSubmit: null, marketExtensionCount: null, marketCheckingLocal: null, marketEmpty: null, marketEmptyDesc: null, marketManualToggleOpen: null, marketManualToggleClose: null,
  },
  'hi-IN': { permissionCurrent: "संदेश अनुमतियाँ", permissionReadOnly: "केवल पढ़ना", permissionReadOnlyDesc: "पढ़ें और खोजें; फ़ाइल बदलावों के लिए अलग स्वीकृति चाहिए।", permissionWorkspaceWrite: "वर्तमान प्रोजेक्ट", permissionWorkspaceWriteDesc: "इस विश्व के प्रोजेक्ट में पढ़ें और लिखें; बाहर के कार्यों के लिए स्वीकृति चाहिए।", permissionFullAccess: "वैश्विक", permissionFullAccessDesc: "सिस्टम खाते से उपलब्ध फ़ाइलें पढ़ें और लिखें तथा टूल स्वीकृति के बिना कमांड चलाएँ।", artifactReady: "उत्पाद तैयार", artifactFailed: "उत्पाद पंजीकरण विफल", artifactCancelled: "पंजीकरण रद्द", artifactPending: "इस चरण के उत्पादों की जाँच हो रही है…", retry: "पुनः प्रयास करें", retrying: "पुनः प्रयास कर रहे हैं…",
    currentWorld: 'वर्तमान दुनिया:', switchWorld: 'दुनिया बदलें', history: 'संदेश इतिहास', startChat: 'बातचीत शुरू करें', startChatHint: 'इतिहास इसी दुनिया में रहता है। संदेश भेजने के बाद भूमिका काम शुरू करती है।', composer: '{name} को संदेश भेजें', approval: 'स्वीकृति माँगें', worldSettings: 'दुनिया की सेटिंग', restoring: 'स्थानीय दुनियाएँ बहाल हो रही हैं…', modelDefault: 'भूमिका का डिफ़ॉल्ट मॉडल उपयोग करें', modelLabel: 'बातचीत मॉडल', modelTemporary: 'बातचीत का अस्थायी चयन',
    recruitRoleplay: 'पात्र आमंत्रित करें', recruitNormal: 'पात्र जोड़ें', recruitDesc: 'टेम्पलेट से स्वतंत्र इंस्टेंस बनाएं।', recruitSearch: 'टेम्पलेट खोजें…', recruitClearSearch: 'खोज साफ़ करें', recruitEmpty: 'कोई टेम्पलेट नहीं मिला।', recruitReading: 'टेम्पलेट लोड हो रहे हैं…', recruitNoCompatible: 'कोई संगत टेम्पलेट नहीं।', recruitExistingCount: 'वर्तमान में {count} मौजूद', recruitSelectPrompt: 'एक टेम्पलेट चुनें', recruitCreateForWorld: 'निर्माण होगा: {name}', recruitCreating: 'बना रहे हैं…', recruitReadingCatalog: 'लोड हो रहा है…', recruitCreateAnother: 'एक और बनाएं', recruitInvite: 'आमंत्रित करें', recruitConfirmAdd: 'जोड़ना सुनिश्चित करें', recruitRoleName: 'नाम (वैकल्पिक)', recruitDuplicateNameWarning: 'यह नाम पहले से मौजूद है।', recruitFullAccessConfirm: 'पूर्ण पहुँच की पुष्टि करता हूँ', recruitFullAccessHint: 'संशोधित होने तक सक्रिय रहेगा।', recruitSkillsLegend: 'पात्र कौशल', recruitNoSkills: 'कोई कौशल नहीं माँगा गया', recruitCapabilitiesLegend: 'मूल क्षमताएँ', recruitNoCapabilities: 'कोई अतिरिक्त क्षमता नहीं', recruitNotice: 'सुरक्षित सुविधाएँ डिफ़ॉल्ट रूप से चुनी गई हैं।', cancel: 'रद्द करें',
    traceTitle: 'दुनिया का ट्रैक', traceSubtitle: 'निर्णय सारांश व टोकन उपयोग', traceRefresh: 'ताज़ा करें', traceCount: '{count} ट्रैक', traceNoTokens: 'टोकन नहीं मिले', traceLiveUpdate: 'लाइव अपडेट', traceActorStats: 'पात्र अनुसार टोकन', traceUnknownActor: 'अज्ञात पात्र',
    // Not translated for this locale yet; the runtime falls back to en-US.
    traceLoadMore: null, traceLoading: null, traceViews: null, traceViewTrace: null, traceViewContext: null, groupCurrentWorld: null, groupTitle: null, groupSubtitle: null, groupSearch: null, groupName: null, groupNamePlaceholder: null, groupMode: null, groupModeDiscussion: null, groupModeDiscussionDesc: null, groupModeTask: null, groupModeTaskDesc: null, groupSelectedCount: null, groupCreating: null, groupCreateSubmit: null, marketTitle: null, marketSubtitle: null, marketTabTheme: null, marketTabThemeDesc: null, marketTabTalent: null, marketTabTalentDesc: null, marketTabPlugin: null, marketTabPluginDesc: null, marketTabSkin: null, marketTabSkinDesc: null, marketSearchPlaceholder: null, marketSearchSubmit: null, marketExtensionCount: null, marketCheckingLocal: null, marketEmpty: null, marketEmptyDesc: null, marketManualToggleOpen: null, marketManualToggleClose: null,
  },
})

for (const [locale, messages] of Object.entries(catalogs) as Array<[UiLocale, Record<string, string>]>) {
  registerMessages(locale, Object.fromEntries(Object.entries(messages).map(([key, value]) => [`workbench.${key}`, value])))
}

export const ALL_WORKBENCH_CATALOGS = catalogs
